### ISSUE TITLE
`NavigationItem` should allow simple click actions

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/vue-components#11]
In order to use this component for Mail, I need to add an entry to the app navigation for the expand/collapse folders feature. This entry neither points to an external URL, nor is it connected to the Vue router. It's a simple "button" with a click action.

Would that be possible, @skjnldsv?

**Comment by skjnldsv** [comment]
@ChristophWurst You have full entries without any feedbacks?
Like what?

Usually the collapsible are managed with a collapsible button, but it's not yet in the standard.
I need to be sure of what you need before adding this :)

**Comment by ChristophWurst** [comment]
The feature works as follows: an IMAP account can have large numbers of folders (mailboxes). Instead of cluttering the UI with these, we hide all non-special (non-inbox, non-sent, non-draft, …) folders be default and instead, show an entry *Show all*. When the users clicks this entry, the full list is shown. On the bottom of the list, there is an entry to collapse the list again.

This could, of course, be implemented as an standard component. But I don't mind implementing this just for Mail as long as this is specific to one app.

**Comment by skjnldsv** [comment]
Ah yes, it make sense!
Let's get this in :)

**Comment by skjnldsv** [comment]
- [ ] add action handler
- [ ] check proper implementation of action or toggleCollapse
- [ ] collapse button option
- [ ] default collapse state
