### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/vue-components#14]
As listed in https://github.com/nextcloud/vue-components/issues/9, we need a standardized avatar component.

@juliushaertl @georgehrke @skjnldsv what should this look like?

IMO this should, for simple use cases, offer to display a colored single-letter avatar like the [image placeholder jQuery plugin in server](https://github.com/nextcloud/server/blob/2e25d22d1693e077ca324804ee208de2eb866040/core/js/placeholder.js), but as a Vue component. Additionally, the component should allow custom URLs to images (on external servers).

**Comment by georgehrke** [comment]
It should also allow to easily add the contacts-menu popover to the avatar. :)

**Comment by skjnldsv** [comment]
Basically the same than we do for the popoverMenu but with the avatar built in?

We still pass the menu, but we also provide the url to the picture? Or should we use displayName/userId and design the component directly? I'm pretty fond of using a direct request to the server since we generate the avatar anyway.
I guess we can also support both, either you provide the url, or the displayName+uid?

**Comment by ChristophWurst** [comment]
> We still pass the menu, but we also provide the url to the picture? Or should we use displayName/userId and design the component directly? I'm pretty fond of using a direct request to the server since we generate the avatar anyway.
> I guess we can also support both, either you provide the url, or the displayName+uid?

Sure, for internal avatars it would be easier to just do the URL magic internally. We just need a way to specify a custom URL for *external* avatars in Mail.

**Comment by ChristophWurst** [comment]
> Just pass the url as a parameter then?

That's exactly what I had in mind (and wrote down above :wink:).

**Comment by juliushaertl** [comment]
> IMO this should, for simple use cases, offer to display a colored single-letter avatar like the image placeholder jQuery plugin in server, but as a Vue component.

The placeholder avatars with letters are also images generated by the server from 14 on, so we should default to the avatar image from the server. If there is none, we can still generate one with some CSS styling. 

:+1: For adding an optional URL parameter to provide an external URL.
