### ISSUE TITLE
[0.1.1] Datepicker "TypeError: Vue.use is not a function"

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/vue-components#24]
Am I doing something wrong? When using the nc-datepicker I get a warning inside of the browser's console. 
`[Vue warn]: Error in render: "TypeError: Vue.use is not a function"`

When I change from 
`import DatePicker from 'nextcloud-vue'` to `import DatePicker from 'vue2-datepicker'` the datepicker works great. 

My main.js:
```javascript
import Vue from 'vue'
import Create from './Create.vue'
//import DatePicker from 'vue2-datepicker'
import DatePicker from 'nextcloud-vue'

Vue.component('DatePickerInput', DatePicker);

new Vue({
  el: '#create-poll',
  render: h => h(Create)
});
```

My Create.vue

```javascript
<template>
	<div id="create-poll" class="flex-column">
		<date-picker-input placeholder="Expiration date" v-model="expire" ></date-picker-input>
	</div>
</template>

<script>
	export default {
		name: 'create-poll',

		data: function () {
			return {
			expire: '',
			}
		}
	}
	
</script>
```

**Comment by skjnldsv** [comment]
Hey :)

You need to use `import {DatePicker} from 'nextcloud-vue'`.
Otherwise you're importing the whole package into the DatePicker variable ;)

**Comment by skjnldsv** [comment]
@dartcafe did it work? :)

**Comment by dartcafe** [comment]
Umpf. no. When I change the line to `import {DatePicker} from 'nextcloud-vue'`, I get the compiling error "export 'DatePicker' was not found in 'nextcloud-vue'

**Comment by skjnldsv** [comment]
@dartcafe ouuups, it's `DatetimePicker` :see_no_evil:

**Comment by dartcafe** [comment]
OMG.  :sunglasses:
