### ISSUE TITLE
Build error from UglifyJs when using vue-componets in production build

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/vue-components#27]
Using the components work perfectly, but I get an error, when building the production build of our polls app. Any hint, what I have to do? I guess, I have a configuration problem. Test builds are working good. 
Regarding https://github.com/nextcloud/polls/tree/vue-create

`ERROR in create-poll.js from UglifyJs
Unexpected token: name (NcVueComponents)`

**Comment by dartcafe** [comment]
I could override this by disabling the exlusion for node_modules in the babel-loader settings. 
webpack.config.js:
```
{
  test: /\.js$/,
  loader: 'babel-loader',
  // exclude: /node_modules/
} 
```

**Comment by skjnldsv** [comment]
@dartcafe I guess this is because you need #26 
Currently we load the vue components instead of the compiled file, so the compilation configuration for this repo needs to be also used on your projects, which is bad and terrible behaviour of course :)

**Comment by dartcafe** [comment]
Works with 0.1.3 👍

**Comment by skjnldsv** [comment]
@dartcafe tha,ks a lot for your feedbacks :hugs:
