### ISSUE TITLE
Autocomplete component

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/vue-components#81]
I'd like to see a component similar to jQuery UI's autocomplete. Mail currently uses that for recipient autocompletion.

@nextcloud/vue would that make sense for other apps as well or is this too specific?

**Comment by ChristophWurst** [comment]
```
$ rg "autocomplete\(" .
core/js/sharedialogview.js
125:                    this.$el.find('.shareWithField').autocomplete("search");
435:                                            .autocomplete("option", "autoFocus", true);
565:                                            .autocomplete('search', $(e.target).val());
602:                                    .autocomplete('search', $(e.target).val());
632:                    $shareWithField.autocomplete('close');
633:                    $shareWithField.autocomplete('disable');
658:                                    $shareWithField.autocomplete('enable');
671:                                    $shareWithField.autocomplete('enable');
684:                                    $shareWithField.autocomplete('enable');
690:                                    $shareWithField.autocomplete('enable');
702:                            $shareWithField.autocomplete('enable');
761:                            $shareField.autocomplete({

```

**Comment by georgehrke** [comment]
> @nextcloud/vue would that make sense for other apps as well or is this too specific?

In calendar there are a couple use-cases:
- [ ] autocomplete for sharing dialog
- [ ] autocomplete for an event's location (based on Contacts' addresses)
- [ ] autocomplete for entering an event's attendees

**Comment by skjnldsv** [comment]
In Contacts we could suggest other contacts on the RELATED field :)

**Comment by skjnldsv** [comment]
Basically you want a dataProvider for the multiselect?

**Comment by ChristophWurst** [comment]
Ah right, multiselect. Yeah, I'll give that a go. The only downside is that we don't have colored avatars there (which the current Mail impl with jQuery UI's autocomplete has).

**Comment by juliushaertl** [comment]
> Ah right, multiselect. Yeah, I'll give that a go. The only downside is that we don't have colored avatars there (which the current Mail impl with jQuery UI's autocomplete has).

We should be able to achieve that with https://vue-multiselect.js.org/#sub-custom-option-template

**Comment by skjnldsv** [comment]
@ChristophWurst Yes, we should always use multiselect. The features are crazy available and it works really great! This is actually an issue on server, we need to use only one solution, this is a nightmare otherwise :)

Currently we have select2, multiselect, jquery autocomplete and now also vue-multiselect! :scream:

**Comment by ChristophWurst** [comment]
Let's just use the multiselect component then :rocket:

**Comment by skjnldsv** [comment]
@ChristophWurst But we can also create a utility to suggest proper data providers from our lib?
